Data Transformation: Once the data is clean the next setp is to reshape, reformate and reorder it as needed for analysis

In [2]:
import pandas as pd
df= pd.read_csv("data1.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [ ]:
#sorting and ranking

In [3]:
df.sort_values("Year") #gives years in sorting values from 2016 to 2023

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [4]:
df.sort_values("Year", ascending = False) #gives descending order from 2023 to 2016

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [9]:
#sorting with multiple columns 
df.sort_values(["Year" ,"IMDb"])# when year has tie then do sorting on base of IMDb

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [10]:
df2 = df.sort_values(["Year" ,"IMDb"]).copy()
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [18]:
df2.sort_index() # it will sort the index in order

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [11]:
df2.reset_index() # it will gives the new index in order and it will not change the df2 data frame it a view not a copy

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,7,Hrithik Roshan,War,2019,Action,475,6.5
7,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [12]:
df2 # hence proved our original data frame is not changed it will change it we use .copy method

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

when reset the dataframe df2 it gives original index as well the new index in order but if want remove the old index and just want new index in order then use drop=True inside reset_index

In [15]:
df2.reset_index(drop=True, inplace=True) #its give view not copy if want copy without copy method use inplace=True

In [17]:
df2#Now df2 is updated without using .copy by using inplace=True

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [21]:
#Ranking
df2['Rank']=df2['IMDb'].rank() # add a rank column with ranking according to IMDb
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0
6,Hrithik Roshan,War,2019,Action,475,6.5,5.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0

In [24]:
df2['Rank']=df2['IMDb'].rank(ascending = False) #ranking descending order
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,10.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,9.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Hrithik Roshan,War,2019,Action,475,6.5,8.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,12.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,11.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [25]:
df2['Rank']=df2['IMDb'].rank(ascending = False, method="dense")#make the ranking in integers and same imdb share same ranking
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [26]:
# reorder the columns
df = df[['Film', 'Actor', 'Year', 'Genre', 'IMDb', 'BoxOffice(INR Crore)']]

In [27]:
df

,Film,Actor,Year,Genre,IMDb,BoxOffice(INR Crore)
0,Pathaan,Shah Rukh Khan,2023,Action,7.2,1050
1,Tiger Zinda Hai,Salman Khan,2017,Action,6.0,565
2,Dangal,Aamir Khan,2016,Biography,8.4,2024
3,Brahmastra,Ranbir Kapoor,2022,Fantasy,5.6,431
4,Padmaavat,Ranveer Singh,2018,Historical,7.0,585
5,Andhadhun,Ayushmann Khurrana,2018,Thriller,8.3,111
6,Stree,Rajkummar Rao,2018,Horror Comedy,7.5,180
7,War,Hrithik Roshan,2019,Action,6.5,475
8,Good Newwz,Akshay Kumar,2019,Comedy,7.0,318
9,Bhool Bhulaiyaa 2,Kartik Aaryan,2022,Horror Comedy,5.9,266
10,Badrinath Ki Dulhania,Varun Dhawan,2017,Romantic Comedy,6.1,201
11,Uri: The Surgical Strike,Vicky Kaushal,2019,Action,8.2,342

In [1]:
#some problems of data transformation

In [3]:
#problem 1: Sort the DataFrame by the Score column in ascending order.
import pandas as pd
data = {
    'Name': ['Ali', 'Zara', 'Hina', 'Fahad'],
    'Score': [88, 75, 95, 60]
}
df = pd.DataFrame(data)
df

    Name  Score
0    Ali     88
1   Zara     75
2   Hina     95
3  Fahad     60

In [6]:
df=df.sort_values(["Score"])
df

    Name  Score
3  Fahad     60
1   Zara     75
0    Ali     88
2   Hina     95

In [7]:
#Problem 2: Sort by Multiple Columns... Sort by Name ascending and Score descending within each name group.
data = {
    'Name': ['Ali', 'Zara', 'Ali', 'Zara'],
    'Subject': ['Math', 'Math', 'English', 'English'],
    'Score': [80, 95, 85, 90]
}
df = pd.DataFrame(data)
df

   Name  Subject  Score
0   Ali     Math     80
1  Zara     Math     95
2   Ali  English     85
3  Zara  English     90

In [13]:
df.sort_values(['Name' ,'Score'], ascending=[True, False])

   Name  Subject  Score
2   Ali  English     85
0   Ali     Math     80
1  Zara     Math     95
3  Zara  English     90

In [14]:
#problem 3: Create a new column "Rank" that ranks students based on Score (highest = rank 1). Use dense ranking (no gaps in ranks).
data = {
    'Student': ['Adeel', 'Sana', 'Hamza', 'Zainab'],
    'Score': [70, 90, 90, 85]
}
df = pd.DataFrame(data)
df

  Student  Score
0   Adeel     70
1    Sana     90
2   Hamza     90
3  Zainab     85

In [18]:
df["Rank"]=df["Score"].rank(ascending=False, method="dense")

In [19]:
df

  Student  Score  Rank
0   Adeel     70   3.0
1    Sana     90   1.0
2   Hamza     90   1.0
3  Zainab     85   2.0

In [20]:
#problem 4:First, sort the DataFrame by Age in descending order. Then, reset the index to reflect the new order (drop old index).
data = {
    'Name': ['Ali', 'Zara', 'Hina', 'Fahad'],
    'Age': [25, 30, 22, 28]
}
df = pd.DataFrame(data)
df

    Name  Age
0    Ali   25
1   Zara   30
2   Hina   22
3  Fahad   28

In [28]:
df2 = df.sort_values(['Age'], ascending = False)
df2

    Name  Age
1   Zara   30
3  Fahad   28
0    Ali   25
2   Hina   22

In [31]:
df2.reset_index(drop =True)

    Name  Age
0   Zara   30
1  Fahad   28
2    Ali   25
3   Hina   22